# Generated by Django 5.2.8 on 2026-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pub', 'published'), ('drf', 'draft')], max_length=20),
        ),
    ]
