# Generated by Django 5.2.8 on 2026-03-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(choices=[('BAVARIA', 'Bavaria'), ('BADEN-WURTTEMBERG', 'Baden-wurttemburg'), ('NORTH RHINE-WESTPHALIA', 'North Rhine-Westphalia'), ('BERLIN', 'Berlin'), ('HAMBURG', 'Hamburg')]),
        ),
    ]
