# Generated by Django 5.2.8 on 2026-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(choices=[('BAVARIA', 'Bavaria'), ('BADEN-WURTTEMBERG', 'Baden-wurttemburg'), ('NORTH RHINE-WESTPHALIA', 'North Rhine-Westphalia'), ('BERLIN', 'Berlin'), ('HAMBURG', 'Hamburg'), ('BRANDENBURG', 'Brandenburg'), ('BREMEN', 'Bremen'), ('HESSEN', 'Hessen'), ('MECKLENBURG-VORPOMMERN', 'Mecklenburg‑Vorpommern'), ('NIEDERSACHSEN', 'Niedersachsen'), ('RHEINLAND-PFALZ', 'Rheinland‑Pfalz'), ('SAARLAND', 'Saarland'), ('SACHSEN', 'Sachsen '), ('SACHSEN-ANHALT', 'Sachsen‑Anhalt')]),
        ),
    ]
